name: profold_env
channels:
  - conda-forge
  - bioconda
  - https://conda.rosettacommons.org
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - biopython=1.85
  - bzip2=1.0.8
  - ca-certificates=2025.11.12
  - certifi=2025.8.3
  - gawk=5.3.1
  - gmp=6.3.0
  - gzip=1.14
  - hhsuite=3.3.0
  - ld_impl_linux-64=2.44
  - libasprintf=0.25.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libexpat=2.7.1
  - libffi=3.5.2
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgettextpo=0.25.1
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libgomp=15.2.0
  - libiconv=1.18
  - liblapack=3.9.0
  - liblzma=5.8.1
  - libnsl=2.0.1
  - libopenblas=0.3.30
  - libsqlite=3.51.0
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libuuid=2.41.2
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - mafft=7.526
  - mpfr=4.2.1
  - ncurses=6.5
  - numpy=2.0.2
  - openssl=3.6.0
  - perl=5.32.1
  - pip=25.2
  - pyrosetta=2025.45+release.d79cb06334
  - python=3.9.23
  - python_abi=3.9
  - readline=8.2
  - setuptools=80.9.0
  - tk=8.6.13
  - tzdata=2025b
  - wheel=0.45.1
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - click==8.1.8
      - filelock==3.19.1
      - fsspec==2025.9.0
      - jinja2==3.1.6
      - markupsafe==2.1.5
      - mpmath==1.3.0
      - networkx==3.2.1
      - packaging==25.0
      - py3dmol==2.5.3
      - pyqt6==6.10.0
      - pyqt6-qt6==6.10.0
      - pyqt6-sip==13.10.2
      - pyqt6-webengine==6.10.0
      - pyqt6-webengine-qt6==6.10.0
      - qdarkstyle==3.2.3
      - qtpy==2.4.3
      - sympy==1.14.0
      - torch==2.8.0+cpu
      - typing-extensions==4.15.0
